/**
 * Seed list of Indian engineering colleges. Format per entry: "Name | City | Kind".
 * Kind: IIT, NIT, IIIT, Central, State, Private, Deemed.
 * This is a starting list, not an exhaustive registry — students can add a college that is missing
 * (stored as unverified) and it is reviewed from the admin dashboard.
 */
const RAW: Record<string, string[]> = {
  "Telangana": [
    "IIT Hyderabad | Sangareddy | IIT",
    "IIIT Hyderabad | Hyderabad | IIIT",
    "BITS Pilani Hyderabad Campus | Hyderabad | Deemed",
    "NIT Warangal | Warangal | NIT",
    "JNTU Hyderabad | Hyderabad | State",
    "JNTUH College of Engineering Sultanpur | Sangareddy | State",
    "Osmania University College of Engineering | Hyderabad | State",
    "Chaitanya Bharathi Institute of Technology (CBIT) | Hyderabad | Private",
    "VNR Vignana Jyothi Institute of Engineering and Technology | Hyderabad | Private",
    "Vasavi College of Engineering | Hyderabad | Private",
    "Gokaraju Rangaraju Institute of Engineering and Technology (GRIET) | Hyderabad | Private",
    "MVSR Engineering College | Hyderabad | Private",
    "Sreenidhi Institute of Science and Technology (SNIST) | Hyderabad | Private",
    "CVR College of Engineering | Hyderabad | Private",
    "Mahindra University | Hyderabad | Private",
    "BVRIT Hyderabad College of Engineering for Women | Hyderabad | Private",
    "Keshav Memorial Institute of Technology (KMIT) | Hyderabad | Private",
    "Anurag University | Hyderabad | Private",
    "Malla Reddy College of Engineering and Technology | Hyderabad | Private",
    "Malla Reddy Engineering College | Hyderabad | Private",
    "Matrusri Engineering College | Hyderabad | Private",
    "MLR Institute of Technology | Hyderabad | Private",
    "Vardhaman College of Engineering | Hyderabad | Private",
    "Institute of Aeronautical Engineering (IARE) | Hyderabad | Private",
    "CMR College of Engineering and Technology | Hyderabad | Private",
    "CMR Institute of Technology Hyderabad | Hyderabad | Private",
    "Neil Gogte Institute of Technology (NGIT) | Hyderabad | Private",
    "TKR College of Engineering and Technology | Hyderabad | Private",
    "Geethanjali College of Engineering and Technology | Hyderabad | Private",
    "St. Martin's Engineering College | Hyderabad | Private",
    "Guru Nanak Institutions Technical Campus | Hyderabad | Private",
    "Hyderabad Institute of Technology and Management (HITAM) | Hyderabad | Private",
    "Methodist College of Engineering and Technology | Hyderabad | Private",
    "Kakatiya Institute of Technology and Science (KITS) | Warangal | Private",
    "SR University | Warangal | Private",
    "Kakatiya University | Warangal | State",
    "Jawaharlal Nehru Technological University Manthani | Peddapalli | State",
    "Sphoorthy Engineering College | Hyderabad | Private",
    "Aurora's Technological and Research Institute | Hyderabad | Private",
    "Sri Indu College of Engineering and Technology | Hyderabad | Private",
    "Marri Laxman Reddy Institute of Technology | Hyderabad | Private",
    "ICFAI Foundation for Higher Education | Hyderabad | Deemed",
    "Sreyas Institute of Engineering and Technology | Hyderabad | Private",
  ],
  "Andhra Pradesh": [
    "IIT Tirupati | Tirupati | IIT",
    "IIIT Sri City | Sri City | IIIT",
    "IIITDM Kurnool | Kurnool | IIIT",
    "IIIT RK Valley (RGUKT) | Idupulapaya | State",
    "NIT Andhra Pradesh | Tadepalligudem | NIT",
    "JNTU Kakinada | Kakinada | State",
    "JNTU Anantapur | Anantapur | State",
    "Andhra University College of Engineering | Visakhapatnam | State",
    "Sri Venkateswara University College of Engineering | Tirupati | State",
    "GITAM University | Visakhapatnam | Deemed",
    "KL University (Koneru Lakshmaiah) | Vaddeswaram | Deemed",
    "VIT-AP University | Amaravati | Private",
    "SRM University AP | Amaravati | Private",
    "Vignan's Foundation for Science, Technology and Research | Guntur | Deemed",
    "V R Siddhartha Engineering College | Vijayawada | Private",
    "Prasad V Potluri Siddhartha Institute of Technology | Vijayawada | Private",
    "Gudlavalleru Engineering College | Gudlavalleru | Private",
    "Aditya Engineering College | Surampalem | Private",
    "Raghu Engineering College | Visakhapatnam | Private",
    "Anil Neerukonda Institute of Technology and Sciences (ANITS) | Visakhapatnam | Private",
    "Lakireddy Bali Reddy College of Engineering | Mylavaram | Private",
    "RVR & JC College of Engineering | Guntur | Private",
    "Narasaraopeta Engineering College | Narasaraopet | Private",
    "Vasireddy Venkatadri Institute of Technology | Guntur | Private",
    "Sir C R Reddy College of Engineering | Eluru | Private",
    "Bapatla Engineering College | Bapatla | Private",
    "Sri Venkateswara College of Engineering Tirupati | Tirupati | Private",
    "Annamacharya Institute of Technology and Sciences | Rajampet | Private",
    "Mohan Babu University (Sree Vidyanikethan) | Tirupati | Private",
    "Pragati Engineering College | Surampalem | Private",
    "Swarnandhra College of Engineering and Technology | Narsapur | Private",
    "Dhanekula Institute of Engineering and Technology | Vijayawada | Private",
    "Vishnu Institute of Technology | Bhimavaram | Private",
    "Shri Vishnu Engineering College for Women | Bhimavaram | Private",
    "Sri Vasavi Engineering College | Tadepalligudem | Private",
    "Chalapathi Institute of Engineering and Technology | Guntur | Private",
    "MVGR College of Engineering | Vizianagaram | Private",
    "Gayatri Vidya Parishad College of Engineering | Visakhapatnam | Private",
    "Andhra Loyola Institute of Engineering and Technology | Vijayawada | Private",
  ],
  "Tamil Nadu": [
    "IIT Madras | Chennai | IIT",
    "NIT Tiruchirappalli | Tiruchirappalli | NIT",
    "IIITDM Kancheepuram | Chennai | IIIT",
    "IIIT Tiruchirappalli | Tiruchirappalli | IIIT",
    "Anna University (CEG Guindy) | Chennai | State",
    "Madras Institute of Technology (MIT Chennai) | Chennai | State",
    "SRM Institute of Science and Technology | Kattankulathur | Deemed",
    "SRM Institute of Science and Technology Ramapuram | Chennai | Deemed",
    "VIT Vellore | Vellore | Deemed",
    "VIT Chennai | Chennai | Deemed",
    "Sathyabama Institute of Science and Technology | Chennai | Deemed",
    "SASTRA Deemed University | Thanjavur | Deemed",
    "PSG College of Technology | Coimbatore | Private",
    "PSG Institute of Technology and Applied Research | Coimbatore | Private",
    "Coimbatore Institute of Technology | Coimbatore | Private",
    "Kumaraguru College of Technology | Coimbatore | Private",
    "Amrita Vishwa Vidyapeetham Coimbatore | Coimbatore | Deemed",
    "Thiagarajar College of Engineering | Madurai | Private",
    "Kalasalingam Academy of Research and Education | Krishnankoil | Deemed",
    "SSN College of Engineering | Chennai | Private",
    "Saveetha Engineering College | Chennai | Private",
    "Saveetha Institute of Medical and Technical Sciences (SIMATS) | Chennai | Deemed",
    "Hindustan Institute of Technology and Science | Chennai | Deemed",
    "Sri Krishna College of Engineering and Technology | Coimbatore | Private",
    "Bannari Amman Institute of Technology | Sathyamangalam | Private",
    "Kongu Engineering College | Perundurai | Private",
    "KPR Institute of Engineering and Technology | Coimbatore | Private",
    "Rajalakshmi Engineering College | Chennai | Private",
    "Sri Sairam Engineering College | Chennai | Private",
    "Velammal Engineering College | Chennai | Private",
    "Easwari Engineering College | Chennai | Private",
    "Panimalar Engineering College | Chennai | Private",
    "St. Joseph's College of Engineering | Chennai | Private",
    "Mepco Schlenk Engineering College | Sivakasi | Private",
    "National Engineering College | Kovilpatti | Private",
    "Government College of Technology Coimbatore | Coimbatore | State",
    "Karunya Institute of Technology and Sciences | Coimbatore | Deemed",
    "Vel Tech Rangarajan Dr. Sagunthala R&D Institute | Chennai | Deemed",
    "B.S. Abdur Rahman Crescent Institute of Science and Technology | Chennai | Deemed",
    "Sri Sivasubramaniya Nadar College of Engineering | Chennai | Private",
    "Chennai Institute of Technology | Chennai | Private",
    "Loyola-ICAM College of Engineering and Technology | Chennai | Private",
    "Sona College of Technology | Salem | Private",
    "Government College of Engineering Salem | Salem | State",
    "Government College of Engineering Tirunelveli | Tirunelveli | State",
    "Alagappa Chettiar Government College of Engineering and Technology | Karaikudi | State",
    "Syed Ammal Engineering College | Ramanathapuram | Private",
    "Jeppiaar Engineering College | Chennai | Private",
    "Meenakshi College of Engineering | Chennai | Private",
    "RMK Engineering College | Chennai | Private",
    "Dr. Mahalingam College of Engineering and Technology | Pollachi | Private",
    "Sri Ramakrishna Engineering College | Coimbatore | Private",
    "Sri Eshwar College of Engineering | Coimbatore | Private",
  ],
  "Karnataka": [
    "IISc Bangalore | Bengaluru | Central",
    "IIIT Bangalore | Bengaluru | IIIT",
    "IIIT Dharwad | Dharwad | IIIT",
    "IIIT Raichur | Raichur | IIIT",
    "IIT Dharwad | Dharwad | IIT",
    "NIT Karnataka Surathkal | Mangaluru | NIT",
    "RV College of Engineering | Bengaluru | Private",
    "BMS College of Engineering | Bengaluru | Private",
    "PES University | Bengaluru | Private",
    "M S Ramaiah Institute of Technology | Bengaluru | Private",
    "Dayananda Sagar College of Engineering | Bengaluru | Private",
    "BNM Institute of Technology | Bengaluru | Private",
    "Bangalore Institute of Technology | Bengaluru | Private",
    "Sir M Visvesvaraya Institute of Technology | Bengaluru | Private",
    "Nitte Meenakshi Institute of Technology | Bengaluru | Private",
    "Christ University | Bengaluru | Deemed",
    "Jain University | Bengaluru | Deemed",
    "REVA University | Bengaluru | Private",
    "Presidency University | Bengaluru | Private",
    "Manipal Institute of Technology | Manipal | Deemed",
    "NMAM Institute of Technology | Nitte | Private",
    "KLE Technological University | Hubballi | Private",
    "SDM College of Engineering and Technology | Dharwad | Private",
    "Siddaganga Institute of Technology | Tumakuru | Private",
    "JSS Science and Technology University | Mysuru | State",
    "National Institute of Engineering (NIE) | Mysuru | Private",
    "Malnad College of Engineering | Hassan | Private",
    "Vidyavardhaka College of Engineering | Mysuru | Private",
    "PDA College of Engineering | Kalaburagi | Private",
    "BMS Institute of Technology and Management | Bengaluru | Private",
    "CMR Institute of Technology Bengaluru | Bengaluru | Private",
    "New Horizon College of Engineering | Bengaluru | Private",
    "Acharya Institute of Technology | Bengaluru | Private",
    "AMC Engineering College | Bengaluru | Private",
    "Global Academy of Technology | Bengaluru | Private",
    "Alliance University | Bengaluru | Private",
    "University Visvesvaraya College of Engineering (UVCE) | Bengaluru | State",
    "Canara Engineering College | Mangaluru | Private",
    "St Joseph Engineering College | Mangaluru | Private",
    "Sahyadri College of Engineering and Management | Mangaluru | Private",
    "Alva's Institute of Engineering and Technology | Moodbidri | Private",
    "Sapthagiri College of Engineering | Bengaluru | Private",
    "Ramaiah University of Applied Sciences | Bengaluru | Private",
    "Atria Institute of Technology | Bengaluru | Private",
    "Don Bosco Institute of Technology | Bengaluru | Private",
    "KLS Gogte Institute of Technology | Belagavi | Private",
    "Basaveshwar Engineering College | Bagalkot | Private",
    "Bapuji Institute of Engineering and Technology | Davangere | Private",
    "Jawaharlal Nehru National College of Engineering | Shivamogga | Private",
    "Visvesvaraya Technological University | Belagavi | State",
  ],
  "Kerala": [
    "IIT Palakkad | Palakkad | IIT",
    "NIT Calicut | Kozhikode | NIT",
    "IIIT Kottayam | Kottayam | IIIT",
    "IIST Thiruvananthapuram | Thiruvananthapuram | Central",
    "College of Engineering Trivandrum | Thiruvananthapuram | State",
    "Government Engineering College Thrissur | Thrissur | State",
    "Government Engineering College Barton Hill | Thiruvananthapuram | State",
    "NSS College of Engineering | Palakkad | State",
    "Model Engineering College | Kochi | State",
    "Rajiv Gandhi Institute of Technology | Kottayam | State",
    "TKM College of Engineering | Kollam | Private",
    "Federal Institute of Science and Technology (FISAT) | Angamaly | Private",
    "Rajagiri School of Engineering and Technology | Kochi | Private",
    "Mar Athanasius College of Engineering | Kothamangalam | Private",
    "Cochin University of Science and Technology (CUSAT) | Kochi | State",
    "Amrita Vishwa Vidyapeetham Amritapuri | Kollam | Deemed",
    "Saintgits College of Engineering | Kottayam | Private",
    "SCMS School of Engineering and Technology | Kochi | Private",
    "Toc H Institute of Science and Technology | Kochi | Private",
    "Sree Chitra Thirunal College of Engineering | Thiruvananthapuram | State",
    "Government Engineering College Kozhikode | Kozhikode | State",
    "Vidya Academy of Science and Technology | Thrissur | Private",
    "Sahrdaya College of Engineering and Technology | Thrissur | Private",
  ],
  "Maharashtra": [
    "IIT Bombay | Mumbai | IIT",
    "IIIT Pune | Pune | IIIT",
    "IIIT Nagpur | Nagpur | IIIT",
    "VNIT Nagpur | Nagpur | NIT",
    "VJTI Mumbai | Mumbai | State",
    "COEP Technological University | Pune | State",
    "Institute of Chemical Technology (ICT) | Mumbai | Deemed",
    "Sardar Patel Institute of Technology | Mumbai | Private",
    "Walchand College of Engineering | Sangli | State",
    "Government College of Engineering Aurangabad | Aurangabad | State",
    "Government College of Engineering Karad | Karad | State",
    "Pune Institute of Computer Technology (PICT) | Pune | Private",
    "Vishwakarma Institute of Technology | Pune | Private",
    "MIT World Peace University | Pune | Private",
    "MIT Academy of Engineering | Pune | Private",
    "Symbiosis Institute of Technology | Pune | Deemed",
    "Cummins College of Engineering for Women | Pune | Private",
    "D Y Patil College of Engineering Akurdi | Pune | Private",
    "D Y Patil International University | Pune | Private",
    "K J Somaiya College of Engineering | Mumbai | Private",
    "Thadomal Shahani Engineering College | Mumbai | Private",
    "Fr. Conceicao Rodrigues College of Engineering | Mumbai | Private",
    "Dwarkadas J. Sanghvi College of Engineering | Mumbai | Private",
    "Thakur College of Engineering and Technology | Mumbai | Private",
    "Ramrao Adik Institute of Technology | Navi Mumbai | Private",
    "Pillai College of Engineering | Navi Mumbai | Private",
    "Shri Ramdeobaba College of Engineering and Management | Nagpur | Private",
    "G H Raisoni College of Engineering | Nagpur | Private",
    "Yeshwantrao Chavan College of Engineering | Nagpur | Private",
    "SGGS Institute of Engineering and Technology | Nanded | State",
    "Pimpri Chinchwad College of Engineering | Pune | Private",
    "Sinhgad College of Engineering | Pune | Private",
    "AISSMS College of Engineering | Pune | Private",
    "Bharati Vidyapeeth College of Engineering Pune | Pune | Deemed",
    "NMIMS Mukesh Patel School of Technology | Mumbai | Deemed",
    "Atharva College of Engineering | Mumbai | Private",
    "Terna Engineering College | Navi Mumbai | Private",
    "Vidyalankar Institute of Technology | Mumbai | Private",
    "Xavier Institute of Engineering | Mumbai | Private",
    "Government College of Engineering Amravati | Amravati | State",
    "Government College of Engineering Jalgaon | Jalgaon | State",
    "Rajarambapu Institute of Technology | Sangli | Private",
    "Vishwakarma Institute of Information Technology | Pune | Private",
    "Army Institute of Technology | Pune | Private",
    "Maharashtra Institute of Technology Chhatrapati Sambhajinagar | Aurangabad | Private",
  ],
  "Gujarat": [
    "IIT Gandhinagar | Gandhinagar | IIT",
    "SVNIT Surat | Surat | NIT",
    "IIIT Vadodara | Vadodara | IIIT",
    "IIIT Surat | Surat | IIIT",
    "L D College of Engineering | Ahmedabad | State",
    "Nirma University | Ahmedabad | Private",
    "DA-IICT | Gandhinagar | Private",
    "Pandit Deendayal Energy University (PDEU) | Gandhinagar | Private",
    "CHARUSAT | Changa | Private",
    "Dharmsinh Desai University | Nadiad | Private",
    "Government Engineering College Gandhinagar | Gandhinagar | State",
    "BVM Engineering College | Vallabh Vidyanagar | Private",
    "Government Engineering College Rajkot | Rajkot | State",
    "Gujarat Technological University | Ahmedabad | State",
    "Marwadi University | Rajkot | Private",
    "Parul University | Vadodara | Private",
    "Ganpat University | Mehsana | Private",
    "Faculty of Technology and Engineering, MS University Baroda | Vadodara | State",
    "Adani Institute of Infrastructure Engineering | Ahmedabad | Private",
    "Vishwakarma Government Engineering College | Ahmedabad | State",
    "Sardar Vallabhbhai Patel Institute of Technology | Vasad | Private",
  ],
  "Rajasthan": [
    "IIT Jodhpur | Jodhpur | IIT",
    "MNIT Jaipur | Jaipur | NIT",
    "IIIT Kota | Kota | IIIT",
    "BITS Pilani | Pilani | Deemed",
    "LNMIIT Jaipur | Jaipur | Private",
    "Manipal University Jaipur | Jaipur | Private",
    "Rajasthan Technical University | Kota | State",
    "JECRC University | Jaipur | Private",
    "Poornima College of Engineering | Jaipur | Private",
    "Arya College of Engineering and IT | Jaipur | Private",
    "Government Engineering College Ajmer | Ajmer | State",
    "Jaipur Engineering College and Research Centre | Jaipur | Private",
    "Swami Keshvanand Institute of Technology | Jaipur | Private",
    "Vivekananda Global University | Jaipur | Private",
    "Government Engineering College Bikaner | Bikaner | State",
    "Government Engineering College Kota | Kota | State",
    "Jodhpur Institute of Engineering and Technology | Jodhpur | Private",
    "Amity University Rajasthan | Jaipur | Private",
    "Geetanjali Institute of Technical Studies | Udaipur | Private",
  ],
  "Delhi NCR": [
    "IIT Delhi | New Delhi | IIT",
    "IIIT Delhi | New Delhi | IIIT",
    "NIT Delhi | New Delhi | NIT",
    "Delhi Technological University (DTU) | New Delhi | State",
    "Netaji Subhas University of Technology (NSUT) | New Delhi | State",
    "Indira Gandhi Delhi Technical University for Women | New Delhi | State",
    "Jamia Millia Islamia | New Delhi | Central",
    "Maharaja Agrasen Institute of Technology | New Delhi | Private",
    "Bharati Vidyapeeth College of Engineering Delhi | New Delhi | Private",
    "Maharaja Surajmal Institute of Technology | New Delhi | Private",
    "University School of Information, Communication and Technology (GGSIPU) | New Delhi | State",
    "Guru Tegh Bahadur Institute of Technology | New Delhi | Private",
    "Bhagwan Parshuram Institute of Technology | New Delhi | Private",
    "Amity University Noida | Noida | Private",
    "Jaypee Institute of Information Technology | Noida | Deemed",
    "Galgotias University | Greater Noida | Private",
    "Sharda University | Greater Noida | Private",
    "Bennett University | Greater Noida | Private",
    "Shiv Nadar University | Greater Noida | Private",
    "KIET Group of Institutions | Ghaziabad | Private",
    "ABES Engineering College | Ghaziabad | Private",
    "Ajay Kumar Garg Engineering College | Ghaziabad | Private",
    "IMS Engineering College | Ghaziabad | Private",
    "JSS Academy of Technical Education | Noida | Private",
    "Manav Rachna International Institute | Faridabad | Private",
    "SRM University Delhi-NCR | Sonepat | Private",
    "G L Bajaj Institute of Technology and Management | Greater Noida | Private",
    "Noida Institute of Engineering and Technology | Greater Noida | Private",
    "Gautam Buddha University | Greater Noida | State",
    "Ansal University | Gurugram | Private",
    "The NorthCap University | Gurugram | Private",
    "Inderprastha Engineering College | Ghaziabad | Private",
  ],
  "Uttar Pradesh": [
    "IIT Kanpur | Kanpur | IIT",
    "IIT BHU Varanasi | Varanasi | IIT",
    "MNNIT Allahabad | Prayagraj | NIT",
    "IIIT Allahabad | Prayagraj | IIIT",
    "IIIT Lucknow | Lucknow | IIIT",
    "Harcourt Butler Technical University | Kanpur | State",
    "Kamla Nehru Institute of Technology | Sultanpur | State",
    "Madan Mohan Malaviya University of Technology | Gorakhpur | State",
    "Bundelkhand Institute of Engineering and Technology | Jhansi | State",
    "Dr. A.P.J. Abdul Kalam Technical University (AKTU) | Lucknow | State",
    "Institute of Engineering and Technology Lucknow | Lucknow | State",
    "Babu Banarasi Das University | Lucknow | Private",
    "Integral University | Lucknow | Private",
    "Aligarh Muslim University | Aligarh | Central",
    "United College of Engineering and Research | Prayagraj | Private",
    "Rajkiya Engineering College Ambedkar Nagar | Ambedkar Nagar | State",
    "Rajkiya Engineering College Banda | Banda | State",
    "Rajkiya Engineering College Kannauj | Kannauj | State",
    "Rajkiya Engineering College Sonbhadra | Sonbhadra | State",
    "Shri Ramswaroop Memorial University | Lucknow | Private",
    "Sam Higginbottom University of Agriculture, Technology and Sciences | Prayagraj | Deemed",
    "Pranveer Singh Institute of Technology | Kanpur | Private",
    "Dr. Ambedkar Institute of Technology for Handicapped | Kanpur | State",
  ],
  "Punjab": [
    "IIT Ropar | Rupnagar | IIT",
    "Thapar Institute of Engineering and Technology | Patiala | Deemed",
    "Punjab Engineering College | Chandigarh | Deemed",
    "UIET Panjab University | Chandigarh | State",
    "Chitkara University | Rajpura | Private",
    "Chandigarh University | Mohali | Private",
    "Lovely Professional University | Phagwara | Private",
    "Guru Nanak Dev Engineering College | Ludhiana | State",
    "Punjabi University Patiala | Patiala | State",
    "Guru Nanak Dev University | Amritsar | State",
    "Chandigarh Group of Colleges Landran | Mohali | Private",
    "Sant Longowal Institute of Engineering and Technology | Longowal | Central",
    "IKG Punjab Technical University | Kapurthala | State",
    "Giani Zail Singh Punjab Technical University Campus | Bathinda | State",
    "Rayat Bahra University | Mohali | Private",
    "Lala Lajpat Rai Institute of Engineering and Technology | Moga | Private",
    "NIT Jalandhar | Jalandhar | NIT",
    "Baba Banda Singh Bahadur Engineering College | Fatehgarh Sahib | Private",
  ],
  "Haryana": [
    "IIIT Sonepat | Sonepat | IIIT",
    "NIT Kurukshetra | Kurukshetra | NIT",
    "Deenbandhu Chhotu Ram University of Science and Technology | Murthal | State",
    "J.C. Bose University of Science and Technology (YMCA) | Faridabad | State",
    "Chaudhary Devi Lal University | Sirsa | State",
    "Maharshi Dayanand University | Rohtak | State",
    "Maharishi Markandeshwar University | Ambala | Deemed",
    "BML Munjal University | Gurugram | Private",
    "Guru Jambheshwar University of Science and Technology | Hisar | State",
    "Amity University Haryana | Gurugram | Private",
    "World College of Technology and Management | Gurugram | Private",
    "Geeta Engineering College | Panipat | Private",
    "Lingaya's Vidyapeeth | Faridabad | Deemed",
    "KR Mangalam University | Gurugram | Private",
    "Panipat Institute of Engineering and Technology | Panipat | Private",
  ],
  "Himachal Pradesh and J&K": [
    "NIT Hamirpur | Hamirpur | NIT",
    "IIIT Una | Una | IIIT",
    "IIT Mandi | Mandi | IIT",
    "IIT Jammu | Jammu | IIT",
    "NIT Srinagar | Srinagar | NIT",
    "Jaypee University of Information Technology | Solan | Private",
    "Shoolini University | Solan | Private",
    "Shri Mata Vaishno Devi University | Katra | State",
    "Baddi University of Emerging Sciences and Technologies | Baddi | Private",
    "Central University of Jammu | Jammu | Central",
    "Government College of Engineering and Technology Jammu | Jammu | State",
    "Model Institute of Engineering and Technology | Jammu | Private",
    "Chitkara University Himachal Pradesh | Solan | Private",
    "Himachal Pradesh Technical University | Hamirpur | State",
    "Islamic University of Science and Technology | Awantipora | State",
    "Baba Ghulam Shah Badshah University | Rajouri | State",
    "Cluster University Srinagar | Srinagar | State",
  ],
  "West Bengal": [
    "IIT Kharagpur | Kharagpur | IIT",
    "IIEST Shibpur | Howrah | Central",
    "NIT Durgapur | Durgapur | NIT",
    "IIIT Kalyani | Kalyani | IIIT",
    "Jadavpur University | Kolkata | State",
    "Kalyani Government Engineering College | Kalyani | State",
    "Maulana Abul Kalam Azad University of Technology | Kolkata | State",
    "Heritage Institute of Technology | Kolkata | Private",
    "Institute of Engineering and Management (IEM) | Kolkata | Private",
    "Techno India University | Kolkata | Private",
    "Techno Main Salt Lake | Kolkata | Private",
    "Calcutta Institute of Engineering and Management | Kolkata | Private",
    "Narula Institute of Technology | Kolkata | Private",
    "Haldia Institute of Technology | Haldia | Private",
    "University of Engineering and Management | Kolkata | Private",
    "Netaji Subhash Engineering College | Kolkata | Private",
    "RCC Institute of Information Technology | Kolkata | State",
    "Meghnad Saha Institute of Technology | Kolkata | Private",
    "MCKV Institute of Engineering | Howrah | Private",
    "Jalpaiguri Government Engineering College | Jalpaiguri | State",
    "Siliguri Institute of Technology | Siliguri | Private",
    "Asansol Engineering College | Asansol | Private",
    "Dr. B.C. Roy Engineering College | Durgapur | Private",
    "Future Institute of Engineering and Management | Kolkata | Private",
    "Guru Nanak Institute of Technology Kolkata | Kolkata | Private",
    "JIS College of Engineering | Kalyani | Private",
    "Birbhum Institute of Engineering and Technology | Suri | State",
    "Cooch Behar Government Engineering College | Cooch Behar | State",
  ],
  "Odisha": [
    "IIT Bhubaneswar | Bhubaneswar | IIT",
    "NIT Rourkela | Rourkela | NIT",
    "IIIT Bhubaneswar | Bhubaneswar | IIIT",
    "KIIT University | Bhubaneswar | Deemed",
    "Siksha 'O' Anusandhan (ITER) | Bhubaneswar | Deemed",
    "Veer Surendra Sai University of Technology | Burla | State",
    "College of Engineering and Technology Bhubaneswar | Bhubaneswar | State",
    "Odisha University of Technology and Research | Bhubaneswar | State",
    "Centurion University of Technology and Management | Bhubaneswar | Private",
    "National Institute of Science and Technology (NIST) | Berhampur | Private",
    "Silicon Institute of Technology | Bhubaneswar | Private",
    "C.V. Raman Global University | Bhubaneswar | Private",
    "Trident Academy of Technology | Bhubaneswar | Private",
    "Indira Gandhi Institute of Technology | Sarang | State",
    "Gandhi Institute for Technology | Bhubaneswar | Private",
    "Government College of Engineering Kalahandi | Bhawanipatna | State",
    "Government College of Engineering Keonjhar | Keonjhar | State",
  ],
  "Bihar and Jharkhand": [
    "IIT Patna | Patna | IIT",
    "IIT (ISM) Dhanbad | Dhanbad | IIT",
    "NIT Patna | Patna | NIT",
    "NIT Jamshedpur | Jamshedpur | NIT",
    "IIIT Bhagalpur | Bhagalpur | IIIT",
    "IIIT Ranchi | Ranchi | IIIT",
    "BIT Mesra | Ranchi | Deemed",
    "BIT Patna | Patna | Private",
    "Muzaffarpur Institute of Technology | Muzaffarpur | State",
    "Bhagalpur College of Engineering | Bhagalpur | State",
    "Gaya College of Engineering | Gaya | State",
    "Netaji Subhas Institute of Technology Patna | Patna | State",
    "Birsa Institute of Technology Sindri | Dhanbad | State",
    "Cambridge Institute of Technology | Ranchi | Private",
    "RTC Institute of Technology | Ranchi | Private",
    "Katihar Engineering College | Katihar | State",
    "Darbhanga College of Engineering | Darbhanga | State",
    "Motihari College of Engineering | Motihari | State",
    "Jharkhand University of Technology | Ranchi | State",
    "Arka Jain University | Jamshedpur | Private",
    "Sarala Birla University | Ranchi | Private",
  ],
  "Chhattisgarh": [
    "IIT Bhilai | Bhilai | IIT",
    "NIT Raipur | Raipur | NIT",
    "IIIT Naya Raipur | Naya Raipur | IIIT",
    "Bhilai Institute of Technology | Durg | Private",
    "Chhattisgarh Swami Vivekanand Technical University | Bhilai | State",
    "Government Engineering College Bilaspur | Bilaspur | State",
    "Shri Shankaracharya Technical Campus | Bhilai | Private",
    "Rungta College of Engineering and Technology | Bhilai | Private",
    "Government Engineering College Raipur | Raipur | State",
    "Kalinga University | Naya Raipur | Private",
    "MATS University | Raipur | Private",
    "Disha Institute of Management and Technology | Raipur | Private",
    "Shri Rawatpura Sarkar Institute of Technology | Naya Raipur | Private",
  ],
  "Madhya Pradesh": [
    "IIT Indore | Indore | IIT",
    "MANIT Bhopal | Bhopal | NIT",
    "ABV-IIITM Gwalior | Gwalior | IIIT",
    "IIITDM Jabalpur | Jabalpur | IIIT",
    "IIIT Bhopal | Bhopal | IIIT",
    "SGSITS Indore | Indore | State",
    "Institute of Engineering and Technology DAVV | Indore | State",
    "Madhav Institute of Technology and Science | Gwalior | State",
    "Jabalpur Engineering College | Jabalpur | State",
    "Rajiv Gandhi Proudyogiki Vishwavidyalaya | Bhopal | State",
    "University Institute of Technology RGPV | Bhopal | State",
    "Oriental Institute of Science and Technology | Bhopal | Private",
    "Lakshmi Narain College of Technology | Bhopal | Private",
    "VIT Bhopal University | Bhopal | Private",
    "Sagar Institute of Research and Technology | Bhopal | Private",
    "Medi-Caps University | Indore | Private",
    "Acropolis Institute of Technology and Research | Indore | Private",
    "Shri Vaishnav Vidyapeeth Vishwavidyalaya | Indore | Private",
    "Sanjeev Agrawal Global Educational University | Bhopal | Private",
    "Jaypee University of Engineering and Technology | Guna | Private",
    "Amity University Madhya Pradesh | Gwalior | Private",
    "Truba Institute of Engineering and Information Technology | Bhopal | Private",
    "Institute of Technology and Management Gwalior | Gwalior | Private",
    "Indore Institute of Science and Technology | Indore | Private",
    "Government Engineering College Ujjain | Ujjain | State",
  ],
  "North East": [
    "IIT Guwahati | Guwahati | IIT",
    "NIT Silchar | Silchar | NIT",
    "NIT Meghalaya | Shillong | NIT",
    "NIT Manipur | Imphal | NIT",
    "NIT Mizoram | Aizawl | NIT",
    "NIT Nagaland | Dimapur | NIT",
    "NIT Arunachal Pradesh | Yupia | NIT",
    "NIT Sikkim | Ravangla | NIT",
    "NIT Agartala | Agartala | NIT",
    "IIIT Guwahati | Guwahati | IIIT",
    "IIIT Manipur | Imphal | IIIT",
    "Assam Engineering College | Guwahati | State",
    "Jorhat Engineering College | Jorhat | State",
    "Tezpur University | Tezpur | Central",
    "Assam Don Bosco University | Guwahati | Private",
    "Girijananda Chowdhury University | Guwahati | Private",
    "Royal Global University | Guwahati | Private",
    "Sikkim Manipal Institute of Technology | Majitar | Private",
    "NERIST | Nirjuli | Central",
    "Mizoram University | Aizawl | Central",
    "Tripura Institute of Technology | Agartala | State",
    "Dibrugarh University Institute of Engineering and Technology | Dibrugarh | State",
    "Don Bosco College of Engineering and Technology | Guwahati | Private",
    "Gauhati University Institute of Science and Technology | Guwahati | State",
    "Kaziranga University | Jorhat | Private",
    "Assam University Silchar | Silchar | Central",
  ],
  "Uttarakhand": [
    "IIT Roorkee | Roorkee | IIT",
    "NIT Uttarakhand | Srinagar Garhwal | NIT",
    "Graphic Era University | Dehradun | Deemed",
    "Graphic Era Hill University | Dehradun | Private",
    "UPES Dehradun | Dehradun | Private",
    "DIT University | Dehradun | Private",
    "G.B. Pant Institute of Engineering and Technology | Pauri | State",
    "College of Technology Pantnagar (GBPUAT) | Pantnagar | State",
    "Tula's Institute | Dehradun | Private",
    "Quantum University | Roorkee | Private",
    "Uttaranchal University | Dehradun | Private",
    "THDC Institute of Hydropower Engineering and Technology | Tehri | State",
    "Kumaon Engineering College | Dwarahat | State",
    "Roorkee Institute of Technology | Roorkee | Private",
    "Doon University | Dehradun | State",
    "Women Institute of Technology | Dehradun | State",
    "Himgiri Zee University | Dehradun | Private",
    "Shivalik College of Engineering | Dehradun | Private",
  ],
  "Goa and Puducherry": [
    "IIT Goa | Farmagudi | IIT",
    "NIT Goa | Farmagudi | NIT",
    "BITS Pilani Goa Campus | Zuarinagar | Deemed",
    "Goa College of Engineering | Farmagudi | State",
    "Padre Conceicao College of Engineering | Verna | Private",
    "Don Bosco College of Engineering | Fatorda | Private",
    "Agnel Institute of Technology and Design | Assagao | Private",
    "Pondicherry Engineering College (PTU) | Puducherry | State",
    "Puducherry Technological University | Puducherry | State",
    "Pondicherry University | Puducherry | Central",
    "Manakula Vinayagar Institute of Technology | Puducherry | Private",
    "Sri Manakula Vinayagar Engineering College | Puducherry | Private",
    "Mailam Engineering College | Villupuram | Private",
    "Christ College of Engineering and Technology | Puducherry | Private",
    "NIT Puducherry | Karaikal | NIT",
    "Rajiv Gandhi College of Engineering and Technology | Puducherry | Private",
    "Perunthalaivar Kamarajar Institute of Engineering and Technology | Karaikal | State",
  ],
};

export type CollegeSeed = { slug: string; name: string; city: string; state: string; kind: string };

export const slugify = (s: string) =>
  s
    .toLowerCase()
    .replace(/&/g, " and ")
    .replace(/[^a-z0-9]+/g, "-")
    .replace(/^-+|-+$/g, "");

function build(): CollegeSeed[] {
  const seen = new Set<string>();
  const out: CollegeSeed[] = [];
  for (const [state, rows] of Object.entries(RAW)) {
    for (const row of rows) {
      const [name, city, kind] = row.split("|").map((p) => p.trim());
      const slug = slugify(name);
      if (seen.has(slug)) continue; // keep first occurrence if a name repeats across states
      seen.add(slug);
      out.push({ slug, name, city, state, kind });
    }
  }
  return out;
}

export const COLLEGE_SEED: CollegeSeed[] = build();
